food/urls.py
from . import views
from django.urls import path

app_name='food'
urlpatterns = [
    path("", views.IndexClassView.as_view(), name="index"),
    path("item/", views.item, name="item"),
    # path("<int:item_id>/", views.detail, name="detail"),
    path("<int:pk>/", views.FoodDetail.as_view(), name="detail"),
    # path("add/", views.create_item, name="create_item"),
    path("add/", views.CreateItem.as_view(), name="create_item"),
    path("update/<int:item_id>/", views.update_item, name="update_item"),
    path("delete/<int:item_id>/", views.delete_item, name="delete_item"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from users import views as users_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include("food.urls")),
    path('register/', users_views.register, name="register"),
    path('login/', auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name="users/logout.html"), name="logout"),
    path('profile/', users_views.profile_page, name="profile"),
] 

urlpatterns += [] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Item(models.Model):

    def __str__(self):
        return self.item_name
    
    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    item_name = models.CharField(max_length=20)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500, default="https://lh3.googleusercontent.com/proxy/XY2-s8N-sBqJVpUns28STtU0Y3B_Nygv3dE4W3I5KX_RIAibk63DtSGrEv-1Lk5Aitg-dEgUpnoGYge93n4euRZZTQc2rxODrhNZna3FCCCJ0W2DctKGVBf5c3tW")

    def get_absolute_url(self):
        return reverse("food:detail", kwargs={"pk":self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default="profile_default.png", upload_to="profile_pictures")
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name', 'item_desc', "item_price", "item_image"]

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

food/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import loader
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

from .models import Item
from .forms import ItemForm

def index(request):
    item_list = Item.objects.all()
    # template = loader.get_template('food/index.html')
    context = {
        'item_list':item_list,
    }
    # return HttpResponse(template.render(context, request))
    return render(request, 'food/index.html', context)

class IndexClassView(ListView):
    model = Item
    template_name = 'food/index.html'
    context_object_list = "item_list"

def item(request):
    return HttpResponse("<h1>This is an item view</h1>")

def detail(request, item_id):
    food_item = Item.objects.get(pk=item_id)
    context = {
        'food_item':food_item,
    }
    return render(request, 'food/detail.html', context)
    # return HttpResponse("This is item number: %s" % item_id)

class FoodDetail(DetailView):
    model = Item
    template_name = "food/detail.html"

def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request, 'food/item_form.html', {'form':form})

class CreateItem(CreateView):
    model = Item
    fields = ['item_name', 'item_image', 'item_desc', 'item_price']
    template_name = 'food/item_form.html'

    def form_valid(self, form):
        form.instance.user_name = self.request.user

        return super().form_valid(form)

def update_item(request, item_id):
    item = Item.objects.get(id=item_id)
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request, 'food/item_form.html', {'form':form, 'item':item})

def delete_item(request, item_id):
    item = Item.objects.get(id=item_id)
    if request.method == "POST":
        item.delete()
        return redirect('food:index')
    
    return render(request, 'food/item_delete.html', {'item':item})

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .forms import RegisterForm
# Create your views here.

def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            messages.success(request,f'Welcome {username}, your account has been created')
            return redirect('login')
    else:
        form = RegisterForm()
    return render(request, "users/register.html", {"form":form})

@login_required
def profile_page(request):
    return render(request, 'users/profile.html')

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous"
    />
    <!-- <link rel="stylesheet" href="{% static 'food/style.css' %}" /> -->
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'food:index' %}">Honeyfur's Den</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'food:index' %}"
              >Home <span class="sr-only">(current)</span></a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'food:create_item' %}">Add Item</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Remove Item</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'profile' %}">Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    {% if messages%} {% for msg in messages%}
    <div class="alert alert-{{ msg.tags }}">{{ msg }} {{ msg.tag }}</div>
    {% endfor %} {% endif %} {% block body %} {% endblock %}
    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

food/templates/food/detail.html
{% extends 'food/base.html'%} {% block body %}
<div class="container mt-5">
  <div class="row">
    <div class="col-md-6">
      <img
        src="{{ object.item_image }}"
        alt="{{object.item_name}}"
        width="500px"
      />
    </div>
    <div class="col-md-6">
      <h2>{{object.item_name}}</h2>
      <h3>{{object.item_desc}}</h3>
      <h4>₹{{object.item_price}}</h4>
      <a
        href="{% url 'food:delete_item' object.pk %}"
        class="btn btn-danger mt-5"
        >Delete Item</a
      >
    </div>
  </div>
</div>
{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html'%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Menu</title>
  </head>
  <body>
    <!-- <ul>
      <li>
        <a href="{% url 'food:detail' item.id %}"
        >{{ item.id }} -- {{ item.item_name }}</a
        >
      </li>
    </ul> -->
    {% block body %}
    <div class="container mt-5">
      {% for item in item_list %}
      <div class="row mt-2 mb-2">
        <div class="col-md-3 offset-md-2">
          <img
            class="card"
            height="150px"
            width="200px"
            src="{{ item.item_image }}"
          />
        </div>
        <div class="col-md-4">
          <h3>{{item.item_name}}</h3>
          <h5>{{item.item_desc}}</h5>
          <h6>₹{{item.item_price}}</h6>
          <p class="muted">Added by: {{item.user_name}}</p>
        </div>
        <div class="col-md-2">
          <a
            href="{% url 'food:detail' item.id %}"
            class="btn btn-success mt-2 mb-2"
            >Details</a
          >
          <a href="" class="btn btn-warning">Add to cart</a>
        </div>
      </div>
      {% endfor %}
    </div>
    {% endblock %}
  </body>
</html>

food/templates/food/item_delete.html
{% extends 'food/base.html'%} {% block body %}
<div class="container mt-5">
  <form method="POST">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{ item.item_name}}?</h2>
    <button type="submit" class="btn btn-danger mt-5">Confirm</button>
  </form>
</div>
{% endblock %}

food/templates/food/item_form.html
{% extends 'food/base.html'%} {% load replace_underscore %} {% block body %}
<div class="container mt-5">
  <div class="container" style="margin-top: 10%">
    <div class="row">
      <div class="offset-md-4 col-md-4">
        <div class="card">
          <div class="card-header text-white bg-dark">
            <div class="card-title mt-2 ml-1">Add Item</div>
          </div>
          <div class="card-body">
            <form method="POST">
              {% csrf_token %} {% for field in form %}
              <div class="form-group">
                {{field.name|replace_underscore}}:
                <br />
                {{field}}
              </div>
              {% endfor %}
              <div class="d-flex justify-content-center">
                <button type="submit" class="btn btn-warning mt-3 pl-5 pr-5">
                  Add
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'food/base.html'%} {% block body %}
<div class="container" style="margin-top: 10%">
  <div class="row">
    <div class="offset-md-4 col-md-4">
      <div class="card">
        <div class="card-header text-white bg-dark">
          <div class="card-title mt-2 ml-1">Login</div>
        </div>
        <div class="card-body">
          <form method="POST">
            {% csrf_token %} {% for field in form %}
            <div class="form-group">{{field.name|capfirst}}: {{field}}</div>
            {% endfor %}
            <div class="d-flex justify-content-center">
              <button type="submit" class="btn btn-warning mt-3 pl-5 pr-5">
                Login
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

users/templates/users/logout.html
{% extends 'food/base.html'%} {% block body %}
<div class="container mt-5">
  <h3>You have been logged out</h3>
</div>
{% endblock %}

users/templates/users/profile.html
{% extends 'food/base.html'%} {% block body %}
<div class="container mt-5">
  <h1>Hi, {{ user.username }}!</h1>
  <img src="{{user.profile.image.url}}" height="150px" width="150px" />
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'food/base.html'%} {% block body %}
<div class="container mt-5">
  <div class="container" style="margin-top: 10%">
    <div class="row">
      <div class="offset-md-4 col-md-4">
        <div class="card">
          <div class="card-header text-white bg-dark">
            <div class="card-title mt-2 ml-1">Register</div>
          </div>
          <div class="card-body">
            <form method="POST">
              {% csrf_token %} {% for field in form %}
              <div class="form-group">
                {{field.name|capfirst}}:
                <br />
                {{field}}
              </div>
              {% endfor %}
              <div class="d-flex justify-content-center">
                <button type="submit" class="btn btn-warning mt-3 pl-5 pr-5">
                  Sign Up
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}